### ISSUE TITLE
'Hardware not responding' in IRScrutinizer for Arduino Pro Micro with AGirs installed

### ISSUE THREAD

**Issue by JabberwockPL** [bengtmartensson/HarcHardware#16]
I am trying to use IRScrutinizer with Arduino Pro Micro with AGirs installed. GirsLite responds correctly when queried with serial console, however in IRScrutinizer I always get the error 'Hardware not responding'. What could be the reason for that?

**Comment by bengtmartensson** [comment]
Fixed with recent migration to NrJavaSerial (#1) and fixes to serial stuff.
